title: RMn
description: Software must be accesible.
show_downloads: true
google_analytics: true
theme: jekyll-theme-architect
copyright: © 2018+
baseurl: {% if (site.github.owner_name | downcase | append: ".github.io" != site.github.repository_name and site.github.url | split: "/" | size > 3 %}{{ site.github.repository_name | prepend: "/" }}{% endif %}
